export const english = {
  language: "Language",
  generalInfo: "General Information",
  itinerary: "Itinerary",
  transport: "Transport",
  transportText: "Section under construction",
  outfit: "Outfit",
  gifts: "Gifts",
  kidsInfo: "Kids",
  tips: "Tips",
  generalInfoText: 'Event on February 18, 2023 at the "Quinta Santa Mónica" Hotel, in Lo de Marcos beach, Jalisco, Mex.',
  letsCelebrate: "Union and farewell Momo and Gera",
  mainSubText: "Let's celebrate!",
  footerAppInfo: "This informative-only app was made by Momo & Gera",
  backBtn: "Back",
  dynamics: "Dynamics - 11:00a.m  a 1:00p.m",
  ceremony: "Ceremony - 4:00pm",
  cocktailsAndSnacks: "Cocktails & Snacks - 5:00p.m",
  mariachi: "Mariachi - 6:00p.m a 8:00p.m",
  dinner: "Dinner at Quinta Santa Monica - 9:00p.m",
  continueTheParty: "And let the party continue 'til the body can hold on!",
  outfitText1: "Wear soft and light clothing, women from short to long simple and formal dresses at the same time.",
  outfitText2: "Men: Formal Casual (Not Denim).",
  outfitText3: "Bring a sweater or coat since in February it is very windy and the air is a bit cold.",
  outfitText4: "Tips: It is advisable to wear a hat for a ceremony on the beach.",
  kidsInfoText: "There will be only one bounce house to entertain the children.",
  tip1: "Have cash as there are no banks in Lo de Marcos.",
  tip2: "Do not eat at street stalls unless it is an established place or restaurant (does not apply to Mexicans).",
  tip3: "Do not forget repellent and sunscreen.",
  giftsText: "(To be defined)",
}