export const english = {
  language: "Language",
  generalInfo: "General Information",
  itinerary: "Itinerary",
  transport: "Transport",
  outfit: "Outfit",
  gifts: "Gifts",
  kidsInfo: "Kids",
  tips: "Tips",
  generalInfoText: 'Event on February 18, 2023 at the "Quinta Santa Mónica" Hotel, in Lo de Marcos beach, Jalisco, Mex.',
  letsCelebrate: "Let's celebrate!",
  mainSubText: "We're very happy to have your company!",
  footerAppInfo: "Weeding app is an informative-only app made by Momo & Gera",
  backBtn: "Back",
  dynamics: "Dynamics - 11:00a.m  a 1:00p.m",
  ceremony: "Ceremony - 4:00pm",
  cocktailsAndSnacks: "Cocktails & Snacks - 5:00p.m",
  mariachi: "Mariachi - 6:00p.m a 8:00p.m",
  dinner: "Dinner at Quinta Santa Monica - 9:00p.m",
  continueTheParty: "And let the party continue 'til the body can hold on!"
}