export const spanish = {
  language: "Idioma",
  generalInfo: "Información general",
  itinerary: "Itinerario",
  transport: "Transporte",
  transportText: "Sección en construcción",
  outfit: "Vestimenta",
  gifts: "Regalos",
  kidsInfo: "Niños",
  tips: "Tips",
  generalInfoText: 'Evento el 18 de febrero 2023 en el Hotel "Quinta Santa Mónica", en playa lo de Marcos, Jalisco, Mex.',
  letsCelebrate: "Unión y despedida Momo y Gera",
  mainSubText: "Let's celebrate!",
  footerAppInfo: "Esta aplicación informativa fue creada por Momo & Gera",
  backBtn: "Volver",
  dynamics: "Dinámicas - 11:00a.m  a 1:00p.m",
  ceremony: "Ceremonia - 4:00pm",
  cocktailsAndSnacks: "Cockteles & snacks - 5:00p.m",
  mariachi: "Mariachi - 6:00p.m a 8:00p.m",
  dinner: "Cena en Quinta Santa Mónica - 9:00p.m",
  continueTheParty: "Y que siga la fiesta hasta que el cuerpo aguante!",
  outfitText1: "Llevar ropa suave y ligera, mujeres desde vestidos cortos a largos sencillos y formales al mismo tiempo (No etiqueta).",
  outfitText2: "Hombres: Casual formal (No Mezclilla).",
  outfitText3: "Llevar algún suéter o abrigo ya que en febrero hace mucho viento y el aire es un poco frio.",
  outfitText4: "Tips: Se aconseja llevar sombrero para ceremonia en la playa.",
  kidsInfoText: "Habrá solo un brincolin para entrener a los niños.",
  tip1: "Contar con efectivo ya que no hay bancos en Lo de Marcos.",
  tip2: "No comer en puestos de la calle a menos que sea un lugar o restaurante establecido (no aplica para Mexicanos).",
  tip3: "No olvidar repelente y bloqueador solar.",
  giftsText: "(Por definir)",
}