export const spanish = {
  language: "Idioma",
  generalInfo: "Información general",
  itinerary: "Itinerario",
  transport: "Transporte",
  outfit: "Vestimenta",
  gifts: "Regalos",
  kidsInfo: "Niños",
  tips: "Tips",
  generalInfoText: 'Evento el 18 de febrero 2023 en el Hotel "Quinta Santa Mónica", en playa lo de Marcos, Jalisco, Mex.',
  letsCelebrate: "Let's celebrate!",
  mainSubText: "Estamos muy contentos de contar con tu compañía!",
  footerAppInfo: "Weeding app aplicación informativa creada por Momo & Gera",
  backBtn: "Volver",
  dynamics: "Dinámicas - 11:00a.m  a 1:00p.m",
  ceremony: "Ceremonia - 4:00pm",
  cocktailsAndSnacks: "Cockteles & snacks - 5:00p.m",
  mariachi: "Mariachi - 6:00p.m a 8:00p.m",
  dinner: "Cena en Quinta Santa Mónica - 9:00p.m",
  continueTheParty: "Y que siga la fiesta hasta que el cuerpo aguante!",
}